name: Deploy to Render via Hook

on:
  push:
    branches:
      - master   # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render deploy hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d4vrnjre5dus73al8ahg?key=LhGhmkgmVYw"
